ALTER TABLE IF EXISTS usage_events
    ADD COLUMN IF NOT EXISTS tenant_id TEXT NOT NULL DEFAULT 'tenant_default';

ALTER TABLE IF EXISTS quota_reservations
    ADD COLUMN IF NOT EXISTS tenant_id TEXT NOT NULL DEFAULT 'tenant_default';
ALTER TABLE IF EXISTS quota_reservations
    ADD COLUMN IF NOT EXISTS job_id UUID;
ALTER TABLE IF EXISTS quota_reservations
    ADD COLUMN IF NOT EXISTS committed_units INTEGER NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS jobs
    ADD COLUMN IF NOT EXISTS tenant_id TEXT NOT NULL DEFAULT 'tenant_default';
ALTER TABLE IF EXISTS jobs
    ADD COLUMN IF NOT EXISTS operation TEXT NOT NULL DEFAULT 'generation';
ALTER TABLE IF EXISTS jobs
    ADD COLUMN IF NOT EXISTS provider_id TEXT NOT NULL DEFAULT 'openai-codex';
ALTER TABLE IF EXISTS jobs
    ADD COLUMN IF NOT EXISTS model TEXT NOT NULL DEFAULT 'gpt-image-2';
ALTER TABLE IF EXISTS jobs
    ADD COLUMN IF NOT EXISTS reservation_id UUID;
ALTER TABLE IF EXISTS jobs
    ADD COLUMN IF NOT EXISTS created_at_ms BIGINT NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS jobs
    ADD COLUMN IF NOT EXISTS updated_at_ms BIGINT NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS jobs
    ADD COLUMN IF NOT EXISTS last_error_code TEXT;
ALTER TABLE IF EXISTS jobs
    ADD COLUMN IF NOT EXISTS last_error_message TEXT;
